In [68]:
import pandas as pd

df = pd.read_csv('dataset.csv')

C:\Users\Prasanna\AppData\Local\Temp\ipykernel_11372\3058218090.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('dataset.csv')


In [69]:
df.head()

,Term ID,Class,Description,Status,Effective Date,Type,Notes,TM5,NCL Version
0,010-1886,10,Medical imaging apparatus for use in the field...,A,04/16/2020,GOODS,NaN,NaN,"""11-2020"""
1,010-1889,10,Medical diagnostic apparatus for testing {spec...,A,04/16/2020,GOODS,NaN,NaN,"""11-2020"""
2,028-4345,28,Balancing bird toys,A,04/16/2020,GOODS,Balancing bird toys are bird-shaped educationa...,T,"""11-2020"""
3,009-5776,9,Image intensifier tubes,A,04/16/2020,GOODS,Image intensifier tubes are a type of vacuum t...,T,"""11-2020"""
4,009-5779,9,Sunglasses for pets,A,04/16/2020,GOODS,Sunglasses is acceptable wording; further spec...,T,"""11-2020"""


In [70]:
df.dropna(subset=['Description', 'Class'], inplace=True)

In [71]:
X=df.drop('Class',axis=1)

In [72]:
y=df['Class']

In [73]:
X.shape

(68060, 8)

In [74]:
y.shape

(68060,)

In [75]:
import tensorflow as tf
tf.__version__

'2.15.0'

In [76]:
from tensorflow.keras.layers import Embedding
from tensorflow. keras.preprocessing. sequence import pad_sequences  #for equal length 
from tensorflow.keras.models import Sequential   
from tensorflow. keras.preprocessing.text import one_hot     #converting sentences into onehot representwtion given vocabulary size
from tensorflow. keras.layers import LSTM
from tensorflow. keras.layers import Dense   

In [77]:
values_to_drop = ['A', '200', 'B']
df = df[~df['Class'].isin(values_to_drop)]


In [82]:
df["Class"][4851]

'20'

In [83]:
df

,Term ID,Class,Description,Status,Effective Date,Type,Notes,TM5,NCL Version
0,010-1886,10,Medical imaging apparatus for use in the field...,A,04/16/2020,GOODS,NaN,NaN,"""11-2020"""
1,010-1889,10,Medical diagnostic apparatus for testing {spec...,A,04/16/2020,GOODS,NaN,NaN,"""11-2020"""
2,028-4345,28,Balancing bird toys,A,04/16/2020,GOODS,Balancing bird toys are bird-shaped educationa...,T,"""11-2020"""
3,009-5776,9,Image intensifier tubes,A,04/16/2020,GOODS,Image intensifier tubes are a type of vacuum t...,T,"""11-2020"""
4,009-5779,9,Sunglasses for pets,A,04/16/2020,GOODS,Sunglasses is acceptable wording; further spec...,T,"""11-2020"""
...,...,...,...,...,...,...,...,...,...
68055,004-828,4,Fruitwood lump charcoal,A,08-08-2024,GOODS,"Lump charcoal, also known as natural hardwood ...",NaN,"""12-2024"""
68056,004-829,4,Hydrocarbon gas liquids (HGL) for use as fuel ...,A,08-08-2024,GOODS,NaN,NaN,"""12-2024"""
68057,004-830,4,Liquefied hydrocarbon gas (LHG) for use as fue...,A,08-08-2024,GOODS,NaN,NaN,"""12-2024"""
68058,004-831,4,Natural hardwood charcoal,A,08-08-2024,GOODS,"Natural hardwood charcoal is carbonized wood, ...",NaN,"""12-2024"""


In [84]:
voc_size=5000

In [85]:
messages=X.copy()

In [86]:
messages['Description'][1]

'Medical diagnostic apparatus for testing {specify condition or subject matter tested, e.g., blood sugar levels, cancer cells, DNA, etc.} incorporating recorded operating system software'

In [87]:
messages.reset_index(inplace=True)

In [88]:
import nltk
import re
from nltk.corpus import stopwords

In [89]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Prasanna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [90]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    # print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['Description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [91]:
corpus

['medic imag apparatu use field indic e g iridolog sclerolog etc incorpor record softwar indic function purpos softwar',
 'medic diagnost apparatu test specifi condit subject matter test e g blood sugar level cancer cell dna etc incorpor record oper system softwar',
 'balanc bird toy',
 'imag intensifi tube',
 'sunglass pet',
 'water temperatur gaug',
 'exercis pulley',
 'automobil engin model toy',
 'remot control submarin toy',
 'magnet clip sunglass lens',
 'pork jerki',
 'medic devic use treat diagnos specifi diseas condit integr record oper system softwar sold unit',
 'softwar use calcul transfer store data relat diagnosi treatment eye disord sold compon ophthalm surgic apparatu',
 'medic imag apparatu incorpor medic imag softwar',
 'medic imag apparatu indic medic use e g diagnos medic condit use surgic procedur etc incorpor record softwar indic function purpos softwar',
 'medic imag apparatu indic medic use e g diagnos medic condit use surgic procedur etc incorpor record oper sy

In [92]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[2920,
  4566,
  3909,
  4237,
  3614,
  4011,
  2646,
  4626,
  1056,
  4532,
  3741,
  4345,
  1049,
  3057,
  4011,
  177,
  637,
  3057],
 [2920,
  3325,
  3909,
  4863,
  4256,
  134,
  4239,
  462,
  4863,
  2646,
  4626,
  2275,
  33,
  3734,
  637,
  4592,
  665,
  3741,
  4345,
  1049,
  108,
  2024,
  3057],
 [3995, 4064, 3082],
 [4566, 2648, 1539],
 [1224, 360],
 [4036, 3574, 3872],
 [2835, 2805],
 [2866, 2050, 2148, 3082],
 [3234, 4144, 4381, 3082],
 [2970, 2376, 1224, 2687],
 [4155, 146],
 [2920,
  1142,
  4237,
  874,
  4990,
  4256,
  2231,
  134,
  4155,
  1049,
  108,
  2024,
  3057,
  2610,
  1933],
 [3057,
  4237,
  3763,
  3770,
  4933,
  3936,
  1817,
  2402,
  1474,
  1570,
  385,
  2610,
  707,
  688,
  2298,
  3909],
 [2920, 4566, 3909, 4345, 2920, 4566, 3057],
 [2920,
  4566,
  3909,
  4011,
  2920,
  4237,
  2646,
  4626,
  4990,
  2920,
  134,
  4237,
  2298,
  2937,
  3741,
  4345,
  1049,
  3057,
  4011,
  177,
  637,
  3057],
 [2920,
  4566,
  3909,
  401

In [93]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0 2920 ...  177  637 3057]
 [4863 4256  134 ...  108 2024 3057]
 [   0    0    0 ... 3995 4064 3082]
 ...
 [   0    0    0 ... 4237 4715 2453]
 [   0    0    0 ... 4117 1859 3524]
 [   0    0    0 ... 3131 3872 3741]]


In [94]:
embedded_docs[0]

array([   0,    0, 2920, 4566, 3909, 4237, 3614, 4011, 2646, 4626, 1056,
       4532, 3741, 4345, 1049, 3057, 4011,  177,  637, 3057])

In [132]:

from sklearn.preprocessing import LabelEncoder

In [133]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)



In [141]:
# embedding_vector_features=40
# model=Sequential()
# model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model.add(LSTM(100))
# model.add(Dense(45,activation='softmax'))
# model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
# print(model.summary())

embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(46, activation='softmax'))  # Number of classes as output
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [142]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)


In [143]:
# tf.convert_to_tensor(X_train, dtype=tf.float32)

In [144]:
model.fit(X_train,y_train, validation_data=(X_test,y_test),epochs=10, batch_size=64)


ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).